
server:
  port: 8767

spring:
  application:
    name: config-server
  cloud:
      config:
        label: master #Git分支
        server:
          git:
            uri: https://github.com/linyouru/ConfigServer #Git地址
            searchPaths: respo  # git仓库地址下的相对地址，可以配置多个，用,分割
            username: linyouru
            password: linbin@1208

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




